### ISSUE TITLE
关于微分方程部分的一些小问题

### ISSUE THREAD

**Issue by SuperGrapee** [BlandAlpha/obsidian_math#10]
# 重要的话最先说：这部分写得很好！
### 二阶常系数非齐次线性微分方程
1.第二个特解的公式中，$Q_l^(2)(x)$后面的中括号应该是不小心打错了
<img width="794" alt="截屏2024-08-29 00 04 14" src="https://github.com/user-attachments/assets/41ed9ac4-34d2-412a-9993-667457e5536e">
2.二阶微分方程的求解相对比较复杂，希望下面这些我总结的步骤能够帮助你理清思路：
step1:将方程变形成为y‘’+py‘+qy=f(x)的形式
step2:观察f(x)的形式，例如若为你的笔记中提到的第一种类型，要注意P_n(x)是什么，e^(alphax)中的alpha是多少
step3:解方程y^2+py+q=0，将得到的根与alpha（第一种类型）或（alpha+ibeta）（第二种类型）进行比较，从而确定特解的类型
step4:对特解分别求一次导数和二次导数，根据待定系数法确定待求的系数即可
3.k重复根的情况其实是k重实根情况的延伸（想想欧拉公式），希望这个可以有助于你记忆这些相对繁琐的结论
4.应该是C_1y_1(x)，但我觉得这些都不影响阅读，不想改也没什么关系的
<img width="813" alt="截屏2024-08-29 00 05 06" src="https://github.com/user-attachments/assets/1aaa7f80-b40d-49a5-a9a4-9f8326a78191">

### 欧拉方程
1.如果觉得欧拉方程的通解比较难记忆的话，可以试试采用微分算子的形式，会发现在微分算子形式下面的欧拉方程很简洁
<img width="724" alt="截屏2024-08-29 00 14 32" src="https://github.com/user-attachments/assets/cdf4c7a7-e940-4de1-ae73-2ac3e1f23d33">
关于欧拉方程的理解，这篇文章写的还可以，[欧拉方程](https://zhuanlan.zhihu.com/p/349911260)

### （补充）黎卡提方程
基本的微分方程的类型笔记里都写到了，是很全面的，很不错，但其实考研的题目里面有时会涉及到一种称为黎卡提方程的特殊方程，其实也不能算超纲（因为本质上是算一阶微分方程），只是求解黎卡提方程需要一点点小技巧，这边简单介绍一下，如果傲傲感兴趣的话可以看看，其实很简单的
<img width="840" alt="截屏2024-08-29 00 24 35" src="https://github.com/user-attachments/assets/748ef967-1260-4958-8f55-329c2d72d917">
[Riccati方程](https://math.fandom.com/zh/wiki/Riccati_%E6%96%B9%E7%A8%8B?variant=zh)

微分方程这部分其实结论性的东西也比较多，但为什么解的形式是如此的都是可以严谨证明出来的，证明比较难，看不懂是正常的，多看看我觉得也许能对理解通解的由来，加深通解形式的记忆有所帮助。其实梳理下来也会发现，主要的微分方程类型也就那么几种，最最重要的还是要记住该怎么去做变量替换，然后最后还要把变量换回来，待定系数法求系数。如果觉得黎卡提方程比较困难，也可以完全忽略，黎卡提其实在控制论里用的很多，如果你以后做AI算法的研究，可能也会和他打交道。
请继续加油！

**Comment by BlandAlpha** [comment]
已收到您的反馈，将在核实后于下次commit解决。另外感谢您的知识性补充，会考虑融入笔记之中。

**Comment by SuperGrapee** [comment]
您客气了，有劳您了

CanisAlpha ***@***.***>于2024年9月1日 周日19:21写道：
