### ISSUE TITLE
关于泰勒展开式的一个小问题

### ISSUE THREAD

**Issue by icecliffs** [BlandAlpha/obsidian_math#12]
仙人指路

[泰勒公式](https://publish.obsidian.md/gee-math-2/1-1.+%E5%87%BD%E6%95%B0%E7%9A%84%E6%9E%81%E9%99%90%E4%B8%8E%E8%BF%9E%E7%BB%AD/%E6%B3%B0%E5%8B%92%E5%85%AC%E5%BC%8F)

![image](https://github.com/user-attachments/assets/a6528ae1-8758-4cae-a375-98f06039ec92)

少打了个 $x^2$

$$
(1+x)^a=1+ax+\frac{a(a-1)}{2!}x^2+o(x^2) 
$$

**Comment by BlandAlpha** [comment]
已收到您的反馈，将在核实后于下次commit解决。

**Comment by icecliffs** [comment]
加油
