### ISSUE TITLE
【定积分的计算-华里士公式】公式错误

### ISSUE THREAD

**Issue by BlandAlpha** [BlandAlpha/obsidian_math#18]
**描述这个Bug**
公式错误

**具体描述**
某个公式或图片加载错误；

**期望表现**
正偶数的倒数第二项应为 $\frac{1}{2}$

**屏幕截图**
![IMG_8281](https://github.com/user-attachments/assets/823679aa-b7bf-4c83-8706-b11b5b7f966a)

**你正在使用什么设备查看笔记本？**
 - Obsidian网页

**附加上下文**
无

**Comment by Co1Nt** [comment]
包括区间上限是π和2π到正偶数部分也有这个错误
