### ISSUE TITLE
some advice

### ISSUE THREAD

**Issue by SuperGrapee** [BlandAlpha/obsidian_math#2]
**描述这个Bug**
简单的文字细节建议

**具体描述**
1. 渲染问题
2. 公式定义存在争议

**期望表现**
1.  一元函数微分学的微分定义中，引例部分分点第3点多了一个右括号
2. 一元函数微分学的高阶导数定义中，也许等式右边部分的分母应该是：

$$
f^{(n-1)}(x_0) = \lim_{x \to x_0} \frac{f^{(n-2)}(x)-f^{(n-2)}(x_0)}{x-x_0}
$$

该建议的原因是在规范书写习惯中，原函数习惯视为0阶导数，请注意下面的示例：

$$
f^{(1)}(x_0) = \lim_{x \to x_0} \frac{f^{(0)}(x)-f^{(0)}(x_0)}{x-x_0}
$$

**你正在使用什么设备查看笔记本？**
 - Github网页

**傲傲加油！**

**Comment by BlandAlpha** [comment]
已修改，将在下一个提交中看到变化。感谢指正！
