### ISSUE TITLE
关于更新时间的暂时性调整公告

### ISSUE THREAD

**Issue by BlandAlpha** [BlandAlpha/obsidian_math#4]
马上就要半期结课考试了，需要花一些时间在课内科目上。因此：
***
1. 从下周（4月21日）开始**两天一次更新**；
2. 五一假期期间**暂停更新**；
3. **半期结束**后立即恢复正常更新频率。

时间可能根据课内复习进度进行调整。

**Comment by SuperGrapee** [comment]
頑張ってください、更新が楽しみよ！

**Comment by alex-278** [comment]
期待大佬更新，数学没有框架学起来好累

**Comment by BlandAlpha** [comment]
> 期待大佬更新，数学没有框架学起来好累

已经恢复更新了，目前的节奏是周一至周五每日一次提交。祝你学习愉快！

**Comment by SuperGrapee** [comment]
![IMG_4194](https://github.com/user-attachments/assets/871ace3a-5265-40bd-82f4-cbcd9fb5f75f)
我真的改变了很多，发生了那些事情，你会绝交是很自然的事情，但我真的欠你一句对不起。最近的半个月我每天都特别痛苦和内疚，我真的很需要和你聊一聊，让我们平静地聊一聊吧，消息也行，电话也行，见面也行，我只是想和你聊一聊，我真的要撑不下去了...
