### ISSUE TITLE
部分章节的小问题

### ISSUE THREAD

**Issue by SuperGrapee** [BlandAlpha/obsidian_math#9]
### 齐次线性方程组
1. 第一个方程组缺少x_2, 即a11x1+a1x2+...a1nxn=0
2. 有解的条件部分，请注意m和n的大小关系（因为这个矩阵并不一定是方阵），文中所写的条件成立的前提是m<n
3. 关于基础解系的求法，也许你的网课已经说的很明白了，方法可能也更好，但看你在文档里写的求法我有些云里雾里，不妨试试我在高等代数课上学习的一种很清晰的求法：
step1：系数矩阵化为阶梯型
step2：阶梯型矩阵的秩是多少，基础解系中的解向量的数量即为未知数个数减去秩
step3：写出阶梯型矩阵对应的方程组，根据基础解系中解向量的数量=自由未知量的个数，把对应的未知数移动到方程组的右边
step4：分别对每个自由未知量依次进行操作：令其中一个未知量为1，其余为0，求解向量，操作完成后可获得全部解向量
step5：方程组的解即为解向量的所有线性组合

### 极大线性无关部分组
可能线代对于概念的理解要求不是很高，但我希望下面这个高等代数里对于极大线性无关部分组的严格定义可以帮助你更好的理解这个概念，因为这个概念在后续的矩阵运算中很重要：
![image](https://github.com/user-attachments/assets/24823b75-8735-4508-b2d7-de0e898eabbb)

### 向量与向量组的线性相关性
1.正交矩阵：在Note部分中，你提到了旋转矩阵，但请注意这种写法的前提是**逆时针旋转**。
2.判别线性相关的定理：也许是教材上的差异，但其实可以不必强调“n-1”，另外定理3的描述可能不太易于理解，希望下面对于线性相关的严格定义和简单判别方法会对你有帮助：
![image](https://github.com/user-attachments/assets/7d7fa54b-d51d-42cb-a1b6-20b54815bad5)
![image](https://github.com/user-attachments/assets/d54a53ed-2d0b-4fe9-9465-8c907999068c)

### 等价向量组
1.第三行错字“标识”→“表示”

### 克拉默法则
其实关于Cramer Rule更重要的作用是求矩阵的逆，通常我们都会用到下面这个结论：
![image](https://github.com/user-attachments/assets/e0c045d3-e33a-4445-b09f-4dfba00154ea)
其中，A*是指A的伴随矩阵

### 伴随矩阵
1.如同你在note中格外标注的一样，关于伴随矩阵，一个容易出错的地方就是伴随矩阵的编号和常规矩阵元素的编号是**相反的**，请一定要注意这个区别，以免在计算的时候不留神出错误
2.另外，请时刻牢记行列式的值其实就是一个实数或代数，这在涉及到矩阵多项式的时候可能会很有帮助（但不知道你们考不考这个）
3.伴随矩阵的性质那部分很难记的，掌握好Cramer Rule就好了，都能推导出来

### 初等变换与初等矩阵
1.其实虚线分隔的目的就是为了在多步变换中时刻清楚自己要化简的目标是什么，或者要求的目标是什么，熟练以后可以不用再画虚线的（但画虚线能提高准确度的话还是很建议的）

检查了一遍公式的推导和性质等等，基本没什么问题，如果需要行列式的更多计算技巧我这边有资料，另外，一般的线性代数讲义都不会提到线性空间的内容的（大概？），但线性空间、基、维数、子空间、线性变换等等对于全面理解线性代数的本质是很有帮助的，如果感兴趣可以了解一下，包括后面的二次型的本质其实就是对称双线性变换在一组标准基下的矩阵。

**Comment by SuperGrapee** [comment]
另外参考资料在这里，如有需要的话请自取，加油！
[高等代数简明教程（第二版）下册.pdf](https://github.com/user-attachments/files/16740778/default.pdf)
[高等代数简明教程(第二版)上册.pdf](https://github.com/user-attachments/files/16740779/default.pdf)

**Comment by BlandAlpha** [comment]
已针对问题进行修改

**Comment by SuperGrapee** [comment]
谢谢采纳，请继续加油哦

CanisAlpha ***@***.***>于2024年8月26日 周一14:25写道：
